[build]
  publish = "."
  command = "echo 'Static site ready for deployment'"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"